#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &


#$HOME/.config/polybar/launch.sh
$HOME/.config/polybar/launchpoly.sh
$HOME/.config/script/display.sh

nitrogen --restore


bspc monitor HDMI-0 -d 1 2 3 
bspc monitor DVI-0 -d 4 5

bspc wm --reorder-monitors HDMI-0 DVI-0

bspc config border_width         2
bspc config window_gap           4 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
